---
- name: Setting .htpasswd
  template:
    src: DOThtpasswd.j2
    dest: "{{ app_deploy_path }}/.htpasswd"
  when: basic_auth == true or basic_auth_admin == true

- name: Deploying /etc/nginx/conf.d/app.conf
  template:
    src: etc+nginx+conf.d+app.conf.j2
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
  notify:
    - restart nginx